# This is a CI workflow for the NCEPLIBS-sp project.
#
# This workflow builds with all developer options, including address
# sanitizer and code coverage.
#
# Ed Hartnett, 1/8/23
name: developer
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  developer:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:
    
    - name: install-dependencies
      run: |
        sudo apt-get install doxygen
        python3 -m pip install gcovr
        
    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: build-sp
      run: |
        cd sp
        mkdir build 
        cd build
        doxygen --version
        cmake -DOPENMP=ON -DCMAKE_PREFIX_PATH="~/" -DENABLE_DOCS=ON -DCMAKE_Fortran_FLAGS="-g -fprofile-arcs -ftest-coverage -O0 -fsanitize=address" -DCMAKE_BUILD_TYPE=Debug ..
        make -j2 VERBOSE=1

    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          sp/build/docs/html
          
    - name: test-sp
      run: |
        cd sp/build
        ctest --verbose --output-on-failure --rerun-failed

    - name: generate-test-coverage
      run: |
        cd sp/build
        gcovr --root .. -v  --html-details --exclude ../tests --exclude CMakeFiles --print-summary -o test-coverage.html &> /dev/null

    - uses: actions/upload-artifact@v2
      with:
        name: sp-test-coverage
        path: |
              sp/build/*.html 
              sp/build/*.css

