# This is a CI workflow for the NCEPLIBS-sp project.
#
# This workflow builds on Linux with different build options.
#
# Ed Hartnett, 1/8/23
name: Linux
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-10
      CC: gcc-10
    strategy:
      matrix:
        openmp: [ON, OFF]
        sharedlibs: [ON, OFF]
        options: [-DBUILD_D=OFF, -DBUILD_4=OFF, BUILD_8=ON]

    steps:
    
    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: build-sp
      run: |
        cd sp
        mkdir build 
        cd build
        cmake -DOPENMP=${{ matrix.openmp }} -DBUILD_SHARED_LIBS=${{ matrix.sharedlibs }} ${{ matrix.options }} -DCMAKE_INSTALL_PREFIX="~/sp"..
        make -j2 VERBOSE=1
        make install

    - name: test-sp
      run: |
        cd sp/build
        ctest --verbose --output-on-failure --rerun-failed


