name: MacOS
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-11
    strategy:
      matrix:
        openmp: [ON, OFF]

    steps:
    
    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: build-sp
      run: |
        cd sp
        mkdir build 
        cd build
        cmake .. -DOPENMP=${{ matrix.openmp }}
        make -j2

    - name: test-sp
      run: |
        cd sp/build
        ctest --verbose --output-on-failure --rerun-failed

