name: with OPENMP
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
        openmp: [ON, OFF]
    steps:
    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: build_sp
      env: 
        FC: gfortran-9
        CC: gcc-9
      run: |
        cd sp
        mkdir build 
        cd build
        cmake .. -DOPENMP=${{ matrix.openmp }}
        make -j2
    
    - name: test_sp
      run: |
        cd $GITHUB_WORKSPACE/sp/build
        make test

